const events = {
    event_error(data) {},
    client_config(data) {},
    presence_update(data) {},
    profile_update(data) {},
    song_metadata(data) {},
    gameplay_time_update(data) {},
    gameplay_score_update(data) {},
    gameplay_input_update(data) {},
    gameplay_note_update(data) {},
    gameplay_pause(data) {},
    gameplay_resume(data) {},
    gameplay_end(data) {},
    gameplay_skip_song(data) {},
    gameplay_section_change(data) {},
    gameplay_sp_activation(data) {},
    gameplay_star_earned(data) {},
    results_final_score(data) {},
    scene_change(data) {},
}